version: "3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    networks:
      - es-net
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - es-vol:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    container_name: es01
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.0
    networks:
      - es-net
    ports:
      - 5601:5601
    container_name: kibana

volumes:
  es-vol:

networks:
  es-net: