version: "3.1"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    networks:
      - es-net
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      # - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xms512m"
      - discovery.type=single-node
      - xpack.security.enrollment.enabled=true
    volumes:
      - es01-vol:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
      memlock:
        soft: -1
        hard: -1
    container_name: es01
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.0
    networks:
      - es-net
    ports:
      - 5601:5601
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
      - ELASTICSEARCH_HOSTS=http://es01:9200
    depends_on:
      - es01

volumes:
  es01-vol:

networks:
  es-net: